# Generated by Django 3.2.18 on 2023-03-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.TextField(),
        ),
    ]
